---
- hosts: webserver-app 
  become: yes
  tasks:
    - name: Start Apache server
      service:
        name=apache2 state=restarted
        
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
